"""Common helpers: HTML escape, date/duration formatting, severity badges,
colour palettes and the timeline taxonomy used across HTML/XLSX builders."""
from __future__ import annotations

import re
import sys
from datetime import datetime, timezone
from typing import Any

# ---------------------------------------------------------------------------
# Progress (rich if available, plain stdout otherwise)
# ---------------------------------------------------------------------------

try:
    from rich.progress import (
        BarColumn, Progress, SpinnerColumn,
        TaskProgressColumn, TextColumn, TimeElapsedColumn,
    )
    RICH_AVAILABLE = True
except ImportError:
    RICH_AVAILABLE = False


class PlainProgress:
    """Fallback progress bar that writes a simple ASCII bar to stdout."""

    def __init__(self, total: int) -> None:
        self._total = total
        self._done = 0

    def __enter__(self) -> "PlainProgress":
        return self

    def __exit__(self, *_: Any) -> None:
        print()

    def add_task(self, label: str, total: int | None = None) -> int:
        return 0

    def advance(self, task_id: int, advance: int = 1) -> None:
        self._done += advance
        if not self._total:
            return
        pct = int(self._done / self._total * 100)
        bar = "#" * (pct // 4)
        print(f"\r  [{bar:<25}] {pct:3d}%", end="", flush=True)

    def update(self, task_id: int, description: str = "") -> None:
        pass


def make_progress(total: int):
    """Return a progress bar (rich.Progress or PlainProgress fallback)."""
    if RICH_AVAILABLE:
        return Progress(
            SpinnerColumn(),
            TextColumn("[bold cyan]{task.description}"),
            BarColumn(),
            TaskProgressColumn(),
            TimeElapsedColumn(),
        )
    return PlainProgress(total)


# ---------------------------------------------------------------------------
# Formatting / escaping
# ---------------------------------------------------------------------------

def h(v: Any) -> str:
    """HTML-escape a value (handles None and non-strings)."""
    return (str(v)
            .replace("&", "&amp;")
            .replace("<", "&lt;")
            .replace(">", "&gt;")
            .replace('"', "&quot;"))


def fmt_dt(iso: str | None) -> str:
    if not iso:
        return "—"
    try:
        dt = datetime.fromisoformat(str(iso).replace("Z", "+00:00"))
        return dt.strftime("%Y-%m-%d %H:%M UTC")
    except (ValueError, TypeError):
        return h(iso)


def fmt_dur(s: float | int | None) -> str:
    if s is None or s == "":
        return "—"
    try:
        s = int(s)
    except (TypeError, ValueError):
        return str(s)
    return f"{s // 60}m {s % 60:02d}s" if s >= 60 else f"{s}s"


def dfl_label(s: str) -> str:
    """Translate WindowsXXXXDomain / Forest into human form."""
    m = re.match(r"Windows(\d+)(R2)?(Domain|Forest)", s or "")
    if m:
        return f"Windows Server {m.group(1)}{' R2' if m.group(2) else ''}"
    return s or "—"


def msdate(s: str | None) -> str:
    """Convert Microsoft /Date(123…)/ to YYYY-MM-DD."""
    m = re.match(r"/Date\((\d+)\)/", s or "")
    if m:
        return datetime.fromtimestamp(
            int(m.group(1)) / 1000, tz=timezone.utc
        ).strftime("%Y-%m-%d")
    return s or "—"


# ---------------------------------------------------------------------------
# Colour palettes & badges
# ---------------------------------------------------------------------------

SEVERITY_COLORS = {
    "critical":      "#c0392b",
    "high":          "#e74c3c",
    "medium":        "#f39c12",
    "low":           "#3498db",
    "informational": "#95a5a6",
}

CAT_COLORS = [
    "#3498db", "#2ecc71", "#e74c3c", "#f39c12",
    "#9b59b6", "#1abc9c", "#e67e22", "#d35400",
]

SEV_BADGE = {
    "critical":      '<span class="badge sev-crit">CRITICAL</span>',
    "high":          '<span class="badge sev-high">HIGH</span>',
    "medium":        '<span class="badge sev-medium">MEDIUM</span>',
    "low":           '<span class="badge sev-low">LOW</span>',
    "informational": '<span class="badge sev-info">INFO</span>',
}

IR_BADGE = (
    '<span class="badge ir-window" title="Finding inside incident window">'
    '&#9888; EN VENTANA</span>'
)
SYNTHETIC_BADGE = (
    '<span class="badge synthetic" title="Auto-generated by IR engine">'
    '&#128295; SINTETICO</span>'
)

TIMELINE = {
    "immediate": ("Immediate Action", "#e74c3c", "&#9889;"),
    "week":      ("This Week",        "#f39c12", "&#128197;"),
    "month":     ("This Month",       "#3498db", "&#128467;"),
    "quarter":   ("Next Quarter",     "#2ecc71", "&#128198;"),
    "none":      ("Informational",    "#95a5a6", "&#8505;"),
}

GPO_STATUS = {
    0: "All Enabled",
    1: "User Disabled",
    2: "Computer Disabled",
    3: "All Disabled",
}


def txt(data, key: str) -> list[str]:
    """Helper to read an entry from data.txt_files with a default."""
    return data.txt_files.get(key, [])


def warn(msg: str) -> None:
    """Print a stderr warning prefixed for grep-ability."""
    print(f"  [warn] {msg}", file=sys.stderr)
